version: '3'

services:

    app:
        build:
            context: src/
            target: crud_api-test
        container_name: crud_api
        env_file:
            - .env
        depends_on:
            - mysql

        networks:
            - app-tier

    mysql:
        image: mysql:8
        container_name: mysql
        restart: unless-stopped
        tty: true
        volumes:
            - ./mysql/:/docker-entrypoint-initdb.d/
            - mysql_data:/var/lib/mysql
        environment:
            MYSQL_DATABASE: crud_api
            MYSQL_ROOT_PASSWORD: secret
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql

        networks:
            - app-tier

networks:
    app-tier:

volumes:
    mysql_data:
